import LeanSpike
import LeanSpike.LcsDP
import Tier2.XmlTripleChecker
import Tier2.RelationshipStorySelector

#print axioms LeanSpike.inv_field_001
#print axioms LeanSpike.inv_rt_001
#print axioms LeanSpike.atomsEqual_implies_text_and_tag_eq
#print axioms LeanSpike.lcs_matches_are_common_subsequence
#print axioms LeanSpike.lcs_matches_are_longest
#print axioms LeanSpike.lcs_match_indices_strictly_increasing
#print axioms LeanSpike.lcs_partitions_inputs
#print axioms LeanSpike.computeAtomLcsDP_eq_computeAtomLcs
#print axioms LeanSpike.rawMatches_are_longest_relevant
#print axioms Tier2.XmlTripleChecker.checker_sound
#print axioms Tier2.XmlTripleChecker.story_collection_checker_sound
#print axioms Tier2.XmlTripleChecker.validateMoveRanges
#print axioms Tier2.XmlTripleChecker.validateMoveRanges_sound
#print axioms Tier2.XmlTripleChecker.foldMoveRanges_trace_of_valid
#print axioms Tier2.XmlTripleChecker.projectUserNoteTokens_no_reserved
#print axioms Tier2.XmlTripleChecker.projectUserNoteTokens_idempotent
#print axioms Tier2.XmlTripleChecker.projectUserNoteTokens_typed_reserved
#print axioms Tier2.RelationshipStorySelector.direct_binding_selection_complete
#print axioms Tier2.RelationshipStorySelector.aligned_slot_unique_work_item
#print axioms Tier2.RelationshipStorySelector.dedup_preserves_selector_locators
#print axioms Tier2.RelationshipStorySelector.relationship_story_aggregate_sound
