import LeanSpike
import LeanSpike.LcsDP
import Tier2.XmlTripleChecker
import Tier2.RelationshipStorySelector
import Tier2.NoteReferenceIntegrity
import LeanDocxChecker

#print axioms LeanSpike.inv_field_001
#print axioms LeanSpike.inv_rt_001
#print axioms LeanSpike.atomsEqual_implies_text_and_tag_eq
#print axioms LeanSpike.lcs_matches_are_common_subsequence
#print axioms LeanSpike.lcs_matches_are_longest
#print axioms LeanSpike.lcs_match_indices_strictly_increasing
#print axioms LeanSpike.lcs_partitions_inputs
#print axioms LeanSpike.computeAtomLcsDP_eq_computeAtomLcs
#print axioms LeanSpike.rawMatches_are_longest_relevant
#print axioms Tier2.XmlTripleChecker.checker_sound
#print axioms Tier2.XmlTripleChecker.story_collection_checker_sound
#print axioms Tier2.XmlTripleChecker.validateMoveRanges
#print axioms Tier2.XmlTripleChecker.validateMoveRanges_sound
#print axioms Tier2.XmlTripleChecker.foldMoveRanges_trace_of_valid
#print axioms Tier2.XmlTripleChecker.projectUserNoteTokens_no_reserved
#print axioms Tier2.XmlTripleChecker.projectUserNoteTokens_idempotent
#print axioms Tier2.XmlTripleChecker.projectUserNoteTokens_typed_reserved
#print axioms Tier2.RelationshipStorySelector.direct_binding_selection_complete
#print axioms Tier2.RelationshipStorySelector.aligned_slot_unique_work_item
#print axioms Tier2.RelationshipStorySelector.dedup_preserves_selector_locators
#print axioms Tier2.RelationshipStorySelector.relationship_story_aggregate_sound
#print axioms Tier2.ConventionalMainNoteSelector.selected_note_identity_sound
#print axioms Tier2.NoteReferenceIntegrity.admitted_source_partition_complete
#print axioms Tier2.NoteReferenceIntegrity.parsed_inventory_evidence_exact
#print axioms Tier2.NoteReferenceIntegrity.package_note_reference_integrity_sound
#print axioms Tier2.NoteReferenceIntegrity.incomplete_partition_zero_evidence_sound
#print axioms Tier2.NoteReferenceIntegrity.note_integrity_aggregate_pass_sound
#print axioms Tier2.NoteReferenceIntegrity.production_run_request_core_refinement_sound
#print axioms Tier2.ConventionalMainNoteSelector.production_note_selector_exact
#print axioms Tier2.NoteReferenceIntegrity.production_note_scan_exact
#print axioms Tier2.NoteReferenceIntegrity.production_note_integrity_sound
#print axioms Tier2.NoteReferenceIntegrity.production_aggregate_pass_exact
#print axioms Tier2.NoteReferenceIntegrity.production_protocol_v5_serialization_exact
#print axioms Tier2.CommentReferenceIntegrity.Typed.typedByteArrayEqCheck_true_iff
#print axioms Tier2.CommentReferenceIntegrity.Typed.typedXmlEventListEqCheck_true_iff
#print axioms Tier2.CommentReferenceIntegrity.Typed.typed_comment_selector_result_sound
#print axioms Tier2.CommentReferenceIntegrity.Typed.typed_comment_selection_to_realization_sound
#print axioms Tier2.CommentReferenceIntegrity.Typed.typed_admitted_comment_source_set_complete
#print axioms Tier2.CommentReferenceIntegrity.Typed.typed_parsed_comment_inventory_evidence_exact
#print axioms Tier2.CommentReferenceIntegrity.Typed.typed_package_comment_reference_integrity_sound
#print axioms Tier2.CommentReferenceIntegrity.Typed.typed_incomplete_comment_partition_zero_evidence_sound
#print axioms Tier2.CommentReferenceIntegrity.Typed.typed_comment_integrity_aggregate_pass_sound
#print axioms Tier2.NoteReferenceIntegrity.production_run_request_core_v6_refinement_sound
#print axioms executable_comment_selector_refines_typed
#print axioms executable_comment_realization_refines_typed
#print axioms executable_comment_source_set_refines_typed
#print axioms executable_comment_incomplete_refines_typed
#print axioms executable_protocol_utf8_json_refines_typed
