export const IR_VERSION = 1 as const;

export type SourceDescriptor = {
  sha256: string;
  paragraphs: number;
};

export type Rationale = {
  operationId: string;
  text: string;
  visibility: 'internal' | 'external-facing';
};

export type AnnotationAudience = 'internal' | 'external-facing' | 'unspecified';
export type AnnotationSemanticRole = 'drafting-note' | 'substantive-footnote' | 'unspecified';
export type AnnotationSourcePresentation = 'comment' | 'footnote' | 'authored';
export type AnnotationPresentation = 'preserve' | 'comment' | 'footnote' | 'omit';

export type AnnotationPosition = { paragraphId: string; offset: number };
export type AnnotationPointAnchor = { kind: 'point'; point: AnnotationPosition };
export type AnnotationRangeAnchor = { kind: 'range'; start: AnnotationPosition; end: AnnotationPosition };
export type AnnotationAnchor = AnnotationPointAnchor | AnnotationRangeAnchor;

export type AnnotationRunStyle = {
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  color?: string;
  highlight?: 'black' | 'blue' | 'cyan' | 'green' | 'magenta' | 'red' | 'yellow' | 'white' | 'darkBlue' | 'darkCyan' | 'darkGreen' | 'darkMagenta' | 'darkRed' | 'darkYellow' | 'darkGray' | 'lightGray' | 'none';
};

export type AnnotationRun = { text: string; style?: AnnotationRunStyle };
export type AnnotationParagraph = { runs: AnnotationRun[] };
export type CanonicalAnnotation = {
  id: string;
  body: AnnotationParagraph[];
  operationId?: string;
  author?: string;
  initials?: string;
  date?: string;
  replyParentId?: string;
  audience: AnnotationAudience;
  semanticRole: AnnotationSemanticRole;
  readonly sourcePresentation: AnnotationSourcePresentation;
  readonly sourceAnchor: AnnotationAnchor;
  anchor: AnnotationAnchor;
  presentation?: AnnotationPresentation;
};

export type AnnotationPresentationRule = {
  as: AnnotationPresentation;
  prefix?: AnnotationRun[];
  separator?: AnnotationRun[];
  bodyStyle?: AnnotationRunStyle;
};

export type AnnotationPresentationProfile = Partial<Record<AnnotationAudience, AnnotationPresentationRule>>;

export type CompilationProfile = {
  revisionAuthor?: string;
  commentAuthor?: string;
  commentInitials?: string;
  buildDate?: string;
  externalComments: 'include' | 'omit';
  annotationPresentation?: AnnotationPresentationProfile;
};

export type DraftRequirement = {
  id: string;
  description: string;
  satisfiedBy: string[];
  mode: 'all' | 'any';
};

export type RequirementWaiver = {
  requirementId: string;
  authority: string;
  reason: string;
};

export type AtomicChangeSet = {
  id: string;
  operationIds: string[];
};

export type DraftAssertion = {
  id: string;
  kind: 'present' | 'absent';
  text: string;
};

export type SourceParagraph = {
  id: string;
  fingerprint: string;
  style: string;
  originalText: string;
  revisedText: string;
};

/**
 * Deliberate direct character formatting for text generated by one operation.
 * This is intentionally a closed semantic vocabulary, not an OOXML property
 * bag. Omitting a property preserves the selected inherited source template.
 */
export type RunFormat = {
  underline?: 'single';
  highlight?: 'yellow';
};

/** Exact half-open revised-text interval carrying an explicit direct-format overlay. */
export type RunFormatSpan = {
  start: number;
  end: number;
  format: RunFormat;
};

export type InlineEditOperation = SourceParagraph & {
  kind: 'inline-edit';
  operationId: string;
  runFormat?: RunFormat;
  runFormatSpans?: RunFormatSpan[];
};

export type ReplaceSourceOperation = SourceParagraph & {
  kind: 'replace-source';
  operationId: string;
  format: 'inherit-source-paragraph';
  /** Optional unique source text whose run formatting new text inherits. */
  formatSource?: string;
  /** Optional direct formatting overlaid only on generated replacement text. */
  runFormat?: RunFormat;
  runFormatSpans?: RunFormatSpan[];
};

export type DeleteSourceOperation = SourceParagraph & {
  kind: 'delete-source';
  operationId: string;
  format: 'inherit-source-paragraph';
  runFormat?: RunFormat;
  runFormatSpans?: RunFormatSpan[];
};

export type InsertOperation = {
  kind: 'insert-before' | 'insert-after';
  operationId: string;
  anchorId: string;
  revisedText: string;
  styleSourceId?: string;
  /** Optional unique style-source text whose run formatting inserted text inherits. */
  formatSource?: string;
  /** Optional direct formatting overlaid only on the generated insertion text. */
  runFormat?: RunFormat;
  runFormatSpans?: RunFormatSpan[];
};

export type EditOperation =
  | InlineEditOperation
  | ReplaceSourceOperation
  | DeleteSourceOperation
  | InsertOperation;

export type MarkdocEditIR = {
  version: typeof IR_VERSION;
  source: SourceDescriptor;
  scaffold: SourceParagraph[];
  operations: EditOperation[];
  rationales: Rationale[];
  annotations: CanonicalAnnotation[];
  compilation?: CompilationProfile;
  /** Additive v1 fields; omitted legacy IR is treated as having no completeness declarations. */
  requirements?: DraftRequirement[];
  waivers?: RequirementWaiver[];
  changeSets?: AtomicChangeSet[];
  assertions?: DraftAssertion[];
};

export type ValidationIssue = {
  code: string;
  message: string;
  line?: number;
};

export type ValidationResult =
  | { valid: true; ir: MarkdocEditIR }
  | { valid: false; issues: ValidationIssue[] };

export type VerificationCertificate = {
  version: 1;
  sourceSha256Matches: boolean;
  scaffoldComplete: boolean;
  paragraphFingerprintsMatch: boolean;
  operationsAppliedExactlyOnce: boolean;
  rejectAllEqualsSource: boolean;
  acceptAllEqualsClean: boolean;
  /** Semantic run/paragraph/table/section formatting equivalence of source ↔ reject-all. */
  rejectAllFormattingEqualsSource: boolean;
  /** Semantic run/paragraph/table/section formatting equivalence of clean ↔ accept-all. */
  acceptAllFormattingEqualsClean: boolean;
  /** Bounded, actionable details for each semantic formatting projection check. */
  formattingProjections: FormattingProjectionReport;
  unchangedPackagePartsPreserved: boolean;
  unsupportedStructures: string[];
  appliedOperations: string[];
  commentRendering: {
    configurationSource: 'markdoc' | 'api' | 'cli' | 'default';
    buildDate: string;
    revisionAuthor: string;
    commentAuthor?: string;
    commentInitials?: string;
    externalRationalesFound: number;
    internalRationalesFound: number;
    externalCommentsIncluded: boolean;
    internalCommentsIncluded: boolean;
    warnings: string[];
  };
  annotationRendering: {
    profile: AnnotationPresentationProfile;
    profileDigest: string;
    dispositions: Array<{ id: string; audience: AnnotationAudience; as: AnnotationPresentation; lossy: boolean; warning?: string }>;
    warnings: string[];
  };
  /** Exact source/reject and clean/accept replay verdict. */
  projectionPassed: boolean;
  draftCompletenessPassed: boolean;
  deliveryReady: boolean;
  completeness: DraftCompletenessReport;
  /** Conservative aggregate verdict: true only when the artifact is delivery-ready. */
  passed: boolean;
};

export type FormattingProjectionDivergence = {
  scope: 'run' | 'paragraph' | 'table' | 'section';
  property: string;
  kind: 'added' | 'removed' | 'changed';
  expectedValue: string | null;
  actualValue: string | null;
  paragraphIndex: number;
  textSample: string;
};

export type FormattingProjectionDiagnostic = {
  score: number;
  unalignedExpectedParagraphs: number;
  unalignedActualParagraphs: number;
  /** Total number of semantic formatting differences before diagnostic truncation. */
  divergenceCount: number;
  /** First divergences only; capped to keep certificates safe for CLI output. */
  divergences: FormattingProjectionDivergence[];
};

export type FormattingProjectionReport = {
  sourceRejectAll: FormattingProjectionDiagnostic;
  cleanAcceptAll: FormattingProjectionDiagnostic;
};

export type RequirementResult = {
  id: string;
  status: 'satisfied' | 'waived' | 'blocked';
  satisfiedBy: string[];
  missingOperations: string[];
  waiver?: RequirementWaiver;
};

export type ChangeSetResult = {
  id: string;
  complete: boolean;
  appliedOperations: string[];
  missingOperations: string[];
};

export type AssertionResult = DraftAssertion & {
  passed: boolean;
};

export type DraftCompletenessReport = {
  requirements: RequirementResult[];
  changeSets: ChangeSetResult[];
  assertions: AssertionResult[];
  passed: boolean;
};

export type CompileResult = {
  clean: Buffer;
  tracked: Buffer;
  ir: MarkdocEditIR;
  certificate: VerificationCertificate;
};

export type RationaleCommentOptions = {
  author: string;
  initials: string;
};

export type CompileOptions = {
  author?: string;
  date?: Date;
  rationaleComments?: RationaleCommentOptions;
  externalComments?: boolean;
  dangerouslyIncludeInternalComments?: boolean;
  configurationSource?: 'api' | 'cli';
  annotationPresentation?: AnnotationPresentationProfile;
};

export type ImportResult = {
  anchoredSource: Buffer;
  markdoc: string;
  source: SourceDescriptor;
  annotations: CanonicalAnnotation[];
};

export type EditPair = {
  operationId: string;
  kind: EditOperation['kind'];
  anchorId: string;
  before: string;
  after: string;
  contextBefore: string[];
  contextAfter: string[];
  rationales: Rationale[];
  /** @deprecated Read `rationales`; populated only when exactly one rationale exists. */
  rationale?: string;
  /** @deprecated Read `rationales`; populated only when exactly one rationale exists. */
  visibility?: Rationale['visibility'];
  verified?: boolean;
  provenance?: Record<string, string>;
};

export type AdjacentRevisionPair = {
  anchorId: string;
  before: string;
  after: string;
  contextBefore: string[];
  contextAfter: string[];
  labels?: Record<string, string>;
};
