export const IR_VERSION = 1 as const;

export type SourceDescriptor = {
  sha256: string;
  paragraphs: number;
};

export type Rationale = {
  operationId: string;
  text: string;
  category?: string;
};

export type DraftRequirement = {
  id: string;
  description: string;
  satisfiedBy: string[];
  mode: 'all' | 'any';
};

export type RequirementWaiver = {
  requirementId: string;
  authority: string;
  reason: string;
};

export type AtomicChangeSet = {
  id: string;
  operationIds: string[];
};

export type DraftAssertion = {
  id: string;
  kind: 'present' | 'absent';
  text: string;
};

export type SourceParagraph = {
  id: string;
  fingerprint: string;
  style: string;
  originalText: string;
  revisedText: string;
};

/**
 * Deliberate direct character formatting for text generated by one operation.
 * This is intentionally a closed semantic vocabulary, not an OOXML property
 * bag. Omitting a property preserves the selected inherited source template.
 */
export type RunFormat = {
  underline?: 'single';
  highlight?: 'yellow';
};

/** Exact half-open revised-text interval carrying an explicit direct-format overlay. */
export type RunFormatSpan = {
  start: number;
  end: number;
  format: RunFormat;
};

export type InlineEditOperation = SourceParagraph & {
  kind: 'inline-edit';
  operationId: string;
  runFormat?: RunFormat;
  runFormatSpans?: RunFormatSpan[];
};

export type ReplaceSourceOperation = SourceParagraph & {
  kind: 'replace-source';
  operationId: string;
  format: 'inherit-source-paragraph';
  /** Optional unique source text whose run formatting new text inherits. */
  formatSource?: string;
  /** Optional direct formatting overlaid only on generated replacement text. */
  runFormat?: RunFormat;
  runFormatSpans?: RunFormatSpan[];
};

export type DeleteSourceOperation = SourceParagraph & {
  kind: 'delete-source';
  operationId: string;
  format: 'inherit-source-paragraph';
  runFormat?: RunFormat;
  runFormatSpans?: RunFormatSpan[];
};

export type InsertOperation = {
  kind: 'insert-before' | 'insert-after';
  operationId: string;
  anchorId: string;
  revisedText: string;
  styleSourceId?: string;
  /** Optional unique style-source text whose run formatting inserted text inherits. */
  formatSource?: string;
  /** Optional direct formatting overlaid only on the generated insertion text. */
  runFormat?: RunFormat;
  runFormatSpans?: RunFormatSpan[];
};

export type EditOperation =
  | InlineEditOperation
  | ReplaceSourceOperation
  | DeleteSourceOperation
  | InsertOperation;

export type MarkdocEditIR = {
  version: typeof IR_VERSION;
  source: SourceDescriptor;
  scaffold: SourceParagraph[];
  operations: EditOperation[];
  rationales: Rationale[];
  /** Additive v1 fields; omitted legacy IR is treated as having no completeness declarations. */
  requirements?: DraftRequirement[];
  waivers?: RequirementWaiver[];
  changeSets?: AtomicChangeSet[];
  assertions?: DraftAssertion[];
};

export type ValidationIssue = {
  code: string;
  message: string;
  line?: number;
};

export type ValidationResult =
  | { valid: true; ir: MarkdocEditIR }
  | { valid: false; issues: ValidationIssue[] };

export type VerificationCertificate = {
  version: 1;
  sourceSha256Matches: boolean;
  scaffoldComplete: boolean;
  paragraphFingerprintsMatch: boolean;
  operationsAppliedExactlyOnce: boolean;
  rejectAllEqualsSource: boolean;
  acceptAllEqualsClean: boolean;
  /** Semantic run/paragraph/table/section formatting equivalence of source ↔ reject-all. */
  rejectAllFormattingEqualsSource: boolean;
  /** Semantic run/paragraph/table/section formatting equivalence of clean ↔ accept-all. */
  acceptAllFormattingEqualsClean: boolean;
  /** Bounded, actionable details for each semantic formatting projection check. */
  formattingProjections: FormattingProjectionReport;
  unchangedPackagePartsPreserved: boolean;
  unsupportedStructures: string[];
  appliedOperations: string[];
  /** Exact source/reject and clean/accept replay verdict. */
  projectionPassed: boolean;
  draftCompletenessPassed: boolean;
  deliveryReady: boolean;
  completeness: DraftCompletenessReport;
  /** Conservative aggregate verdict: true only when the artifact is delivery-ready. */
  passed: boolean;
};

export type FormattingProjectionDivergence = {
  scope: 'run' | 'paragraph' | 'table' | 'section';
  property: string;
  kind: 'added' | 'removed' | 'changed';
  expectedValue: string | null;
  actualValue: string | null;
  paragraphIndex: number;
  textSample: string;
};

export type FormattingProjectionDiagnostic = {
  score: number;
  unalignedExpectedParagraphs: number;
  unalignedActualParagraphs: number;
  /** Total number of semantic formatting differences before diagnostic truncation. */
  divergenceCount: number;
  /** First divergences only; capped to keep certificates safe for CLI output. */
  divergences: FormattingProjectionDivergence[];
};

export type FormattingProjectionReport = {
  sourceRejectAll: FormattingProjectionDiagnostic;
  cleanAcceptAll: FormattingProjectionDiagnostic;
};

export type RequirementResult = {
  id: string;
  status: 'satisfied' | 'waived' | 'blocked';
  satisfiedBy: string[];
  missingOperations: string[];
  waiver?: RequirementWaiver;
};

export type ChangeSetResult = {
  id: string;
  complete: boolean;
  appliedOperations: string[];
  missingOperations: string[];
};

export type AssertionResult = DraftAssertion & {
  passed: boolean;
};

export type DraftCompletenessReport = {
  requirements: RequirementResult[];
  changeSets: ChangeSetResult[];
  assertions: AssertionResult[];
  passed: boolean;
};

export type CompileResult = {
  clean: Buffer;
  tracked: Buffer;
  ir: MarkdocEditIR;
  certificate: VerificationCertificate;
};

export type RationaleCommentOptions = {
  author: string;
  initials: string;
  date: Date;
};

export type CompileOptions = {
  author?: string;
  date?: Date;
  rationaleComments?: RationaleCommentOptions;
};

export type ImportResult = {
  anchoredSource: Buffer;
  markdoc: string;
  source: SourceDescriptor;
};

export type EditPair = {
  operationId: string;
  kind: EditOperation['kind'];
  anchorId: string;
  before: string;
  after: string;
  contextBefore: string[];
  contextAfter: string[];
  rationale?: string;
  category?: string;
  verified?: boolean;
  provenance?: Record<string, string>;
};

export type AdjacentRevisionPair = {
  anchorId: string;
  before: string;
  after: string;
  contextBefore: string[];
  contextAfter: string[];
  labels?: Record<string, string>;
};
