#!/usr/bin/env node

import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PACKAGE_ROOT = path.resolve(__dirname, '..');
const REPO_ROOT = path.resolve(PACKAGE_ROOT, '..', '..');
const TEST_ROOT = path.join(PACKAGE_ROOT, 'src');
const CANONICAL_SPEC = path.join(REPO_ROOT, 'openspec', 'specs', 'docx-comparison', 'spec.md');
const DEFAULT_MATRIX_PATH = path.join(TEST_ROOT, 'testing', 'DOCX_COMPARISON_OPENSPEC_TRACEABILITY.md');

function normalizeScenarioName(value) {
  return value
    .replace(/^Scenario:\s*/i, '')
    .replace(/^\[[^\]]+\]\s*/, '')
    .trim()
    .replace(/\s+/g, ' ');
}

function parseScenariosFromSpec(content) {
  const scenarios = new Set();
  const scenarioHeader = /^\s*####\s+Scenario:\s*(.+?)\s*$/gm;
  let m = scenarioHeader.exec(content);
  while (m) {
    scenarios.add(normalizeScenarioName(m[1]));
    m = scenarioHeader.exec(content);
  }
  return scenarios;
}

function parseStoriesFromTest(content) {
  const stories = new Set();

  const viaOpenspec = /\.openspec\(\s*(["'`])([\s\S]*?)\1\s*\)/g;
  let m = viaOpenspec.exec(content);
  while (m) {
    stories.add(normalizeScenarioName(m[2]));
    m = viaOpenspec.exec(content);
  }

  const viaAllureStory = /allure\.story\(\s*(["'`])([\s\S]*?)\1\s*\)/g;
  m = viaAllureStory.exec(content);
  while (m) {
    stories.add(normalizeScenarioName(m[2]));
    m = viaAllureStory.exec(content);
  }

  return stories;
}

function parseSkippedStoriesFromTest(content) {
  const skipped = new Set();
  const skippedPattern = /(?:test|it)\.(?:skip|todo)\(\s*(["'`])(?:Scenario:\s*)?([\s\S]*?)\1/g;
  let m = skippedPattern.exec(content);
  while (m) {
    skipped.add(normalizeScenarioName(m[2]));
    m = skippedPattern.exec(content);
  }
  return skipped;
}

async function listFilesRecursively(rootDir, predicate) {
  const out = [];

  async function walk(dir) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
        continue;
      }
      if (predicate(full)) out.push(full);
    }
  }

  await walk(rootDir);
  return out.sort();
}

function mdEscapeTableCell(value) {
  return String(value)
    .replace(/\|/g, '\\|')
    .replace(/\r?\n/g, ' ')
    .trim();
}

function buildMatrixMarkdown({ scenarios, storyToFiles, skippedStories }) {
  const lines = [];
  lines.push('# DOCX Comparison OpenSpec Traceability Matrix');
  lines.push('');
  lines.push('> Auto-generated by `packages/docx-comparison/scripts/validate_openspec_coverage.mjs`.');
  lines.push('> Do not hand-edit this file.');
  lines.push('');
  lines.push('This matrix maps canonical spec `#### Scenario:` entries to scenario mappings extracted from `src/**/*.test.ts`.');
  lines.push('');
  lines.push('| Scenario | Status | Test Files | Notes |');
  lines.push('|---|---|---|---|');

  for (const scenario of scenarios) {
    const files = storyToFiles.get(scenario) ?? [];
    const isSkipped = skippedStories.has(scenario);

    const status = isSkipped
      ? 'pending_impl'
      : files.length > 0
        ? 'covered'
        : 'missing';

    const fileCell = files.length > 0
      ? files.map((f) => `\`${f}\``).join(', ')
      : 'n/a';

    let notes = '';
    if (isSkipped) notes = 'skip/todo in tests';
    else if (files.length === 0) notes = 'No scenario mapping found in current tests';

    lines.push(
      `| ${mdEscapeTableCell(scenario)} | ${status} | ${mdEscapeTableCell(fileCell)} | ${mdEscapeTableCell(notes)} |`,
    );
  }

  lines.push('');
  return `${lines.join('\n')}\n`;
}

function parseArgs() {
  const args = process.argv.slice(2);
  let writeMatrixPath = DEFAULT_MATRIX_PATH;
  let strict = false;

  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === '--write-matrix') {
      const value = args[i + 1];
      if (value && !value.startsWith('--')) {
        writeMatrixPath = path.resolve(process.cwd(), value);
        i += 1;
      }
      continue;
    }
    if (arg === '--strict') {
      strict = true;
      continue;
    }
    throw new Error(`Unknown argument: ${arg}`);
  }

  return { writeMatrixPath, strict };
}

async function main() {
  const { writeMatrixPath, strict } = parseArgs();

  let canonicalSpec;
  try {
    canonicalSpec = await fs.readFile(CANONICAL_SPEC, 'utf-8');
  } catch {
    console.error(`Cannot read canonical spec: ${CANONICAL_SPEC}`);
    process.exitCode = 1;
    return;
  }

  const scenarioSet = parseScenariosFromSpec(canonicalSpec);
  const scenarios = [...scenarioSet].sort();
  if (scenarios.length === 0) {
    console.error(`No '#### Scenario:' entries found in ${CANONICAL_SPEC}`);
    process.exitCode = 1;
    return;
  }

  const testFiles = await listFilesRecursively(TEST_ROOT, (f) => f.endsWith('.test.ts'));

  const storyToFiles = new Map();
  const storySet = new Set();
  const skippedStorySet = new Set();

  for (const tf of testFiles) {
    const content = await fs.readFile(tf, 'utf-8');
    const rel = path.relative(PACKAGE_ROOT, tf).split(path.sep).join('/');

    for (const story of parseStoriesFromTest(content)) {
      storySet.add(story);
      const files = storyToFiles.get(story) ?? [];
      if (!files.includes(rel)) files.push(rel);
      storyToFiles.set(story, files);
    }

    for (const skipped of parseSkippedStoriesFromTest(content)) {
      skippedStorySet.add(skipped);
    }
  }

  const missing = scenarios.filter((scenario) => !storySet.has(scenario));
  const pending = scenarios.filter((scenario) => skippedStorySet.has(scenario));
  const covered = scenarios.length - missing.length;
  const extra = [...storySet].filter((story) => !scenarioSet.has(story)).sort();

  const matrix = buildMatrixMarkdown({
    scenarios,
    storyToFiles,
    skippedStories: skippedStorySet,
  });

  await fs.mkdir(path.dirname(writeMatrixPath), { recursive: true });
  await fs.writeFile(writeMatrixPath, matrix, 'utf-8');

  const pct = ((covered / scenarios.length) * 100).toFixed(1);
  if (missing.length === 0 && pending.length === 0) {
    const extraSuffix = extra.length > 0 ? ` (+${extra.length} additional stories not in spec)` : '';
    console.log(`PASS docx-comparison: ${covered}/${scenarios.length} scenarios mapped (${pct}%)${extraSuffix}`);
  } else {
    const label = strict ? 'FAIL' : 'WARN';
    console.error(`${label} docx-comparison: ${covered}/${scenarios.length} scenarios mapped (${pct}%)`);
    if (missing.length > 0) {
      console.error(`  Missing scenarios (${missing.length}):`);
      for (const scenario of missing) {
        console.error(`    - ${scenario}`);
      }
    }
    if (pending.length > 0) {
      console.error(`  Pending scenarios (${pending.length}):`);
      for (const scenario of pending) {
        console.error(`    - ${scenario}`);
      }
    }
    if (strict) process.exitCode = 1;
  }

  if (extra.length > 0) {
    console.log(`Extra scenario stories not in spec (${extra.length}):`);
    for (const scenario of extra) {
      console.log(`  - ${scenario}`);
    }
  }

  const relative = path.relative(REPO_ROOT, writeMatrixPath).split(path.sep).join('/');
  console.log(`Wrote traceability matrix: ${relative}`);
}

await main();
