#!/usr/bin/env node
// Generates verification/INVARIANTS.md from verification/registry/invariants.json.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REGISTRY_PATH = path.join(REPO_ROOT, 'verification', 'registry', 'invariants.json');
const OUT_PATH = path.join(REPO_ROOT, 'verification', 'INVARIANTS.md');
const TIER_ORDER = ['proven', 'proven-modulo-axiom', 'empirically-validated', 'tested-only'];

function loadRegistry() {
  return JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf8'));
}

function escapeCell(value) {
  return String(value ?? '—')
    .replace(/\|/g, '\\|')
    .replace(/\r?\n/g, '<br>');
}

function code(value) {
  if (value === undefined || value === null || value === '') return '—';
  return `\`${escapeCell(value)}\``;
}

function list(values) {
  if (!Array.isArray(values) || values.length === 0) return '—';
  return values.map((value) => code(value)).join('<br>');
}

function proseList(values) {
  if (!Array.isArray(values) || values.length === 0) return '—';
  return values.map(escapeCell).join('<br>');
}

function render(registry) {
  const lines = [];
  lines.push('# Verification Invariants');
  lines.push('');
  lines.push('<!-- Generated by scripts/generate_invariants_doc.mjs from verification/registry/invariants.json. Do not edit by hand. -->');
  lines.push('');
  lines.push('This document is generated from the machine-readable invariant registry.');
  lines.push('It records today\'s proof and evidence status without collapsing tiers.');
  lines.push('');
  lines.push('## Tier Taxonomy');
  lines.push('');
  lines.push('- `proven` (machine-checked in Lean with no assumptions beyond Lean + mathlib)');
  lines.push('- `proven-modulo-axiom` (machine-checked except for explicitly named residual axioms)');
  lines.push('- `empirically-validated` (established by a deterministic differential harness or property test, not a proof — including Lean↔TS extensional equivalence)');
  lines.push('- `tested-only` (covered by conventional tests, not formally verified)');
  lines.push('');

  for (const tier of TIER_ORDER) {
    const entries = registry.invariants.filter((entry) => entry.tier === tier);
    if (entries.length === 0) continue;
    lines.push(`## ${tier}`);
    lines.push('');
    lines.push('| ID | Statement | Lean theorem / surface | Production surface | Residual axioms | Signature axioms | Caveats | Falsifier |');
    lines.push('| --- | --- | --- | --- | --- | --- | --- | --- |');
    for (const entry of entries) {
      lines.push([
        code(entry.id),
        escapeCell(entry.statement),
        `${code(entry.leanTheorem)}<br>${code(entry.leanFile)}`,
        code(entry.productionSurface),
        list(entry.residualAxioms),
        list(entry.signatureAxioms),
        proseList(entry.caveats),
        escapeCell(entry.falsifier),
      ].join(' | ').replace(/^/, '| ').replace(/$/, ' |'));
    }
    lines.push('');
  }

  return lines.join('\n');
}

function main() {
  const registry = loadRegistry();
  fs.writeFileSync(OUT_PATH, render(registry));
  console.log(`generate_invariants_doc: wrote ${path.relative(REPO_ROOT, OUT_PATH)}`);
}

main();
