#!/usr/bin/env node
// generate_conformance_doc.mjs
//
// Generates `spec-compliance/CONFORMANCE.md`, the full normative-claims
// summary, from `spec-compliance/registry/*.md`.
//
// The drift gate `scripts/check_conformance_doc.mjs` runs this script and
// then `git diff --exit-code` to catch hand edits to the generated output.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadRegistry } from './lib/conformance-registry.mjs';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_CONFORMANCE = path.join(REPO_ROOT, 'spec-compliance', 'CONFORMANCE.md');

// ── Rendering ───────────────────────────────────────────────────────────────

function trimmedProse(prose) {
  return prose.join('\n').trim();
}

// Render the detailed subsection for one registry entry. Shared by targeted
// sections and Non-Goals so both carry identical spec/schema binding; Non-Goals
// pass includeVerifiedBy=false since nothing verifies a non-claim. Always ends
// with a trailing blank line so the caller can append the next block directly.
function renderEntryDetail(lines, e, { includeVerifiedBy }) {
  lines.push(`### ${e.id} — ${e.title}`);
  lines.push('');
  lines.push(`- **Edition:** ECMA-376 ${e.meta.edition ?? '?'}`);
  lines.push(`- **Part / Section:** Part ${e.meta.part ?? '?'} § ${e.meta.section ?? '?'}`);
  lines.push(`- **Canonical URL:** ${e.meta.url ?? '—'}`);
  lines.push(`- **Schema reference:** \`${e.meta.schemaRef ?? '—'}\``);
  if (includeVerifiedBy && (e.meta.verifiedBy ?? '').trim()) {
    lines.push(`- **Verified by:** ${e.meta.verifiedBy}`);
  }
  lines.push('');
  const prose = trimmedProse(e.prose);
  if (prose) {
    lines.push(prose);
    lines.push('');
  }
}

function specFamilyTitle(entries) {
  const families = new Set();
  for (const e of entries) {
    if (e.id.startsWith('ECMA')) families.add('ECMA-376');
    else families.add(e.id.replace(/^([A-Z]+).*$/, '$1'));
  }
  return [...families].sort().join(', ');
}

function renderConformanceMd(registry) {
  const { entries, nonGoals } = registry;
  const lines = [];
  lines.push('# Conformance');
  lines.push('');
  // Editor-facing provenance only; an HTML comment keeps it out of the rendered
  // page (GitHub etc.) while still warning anyone editing the raw Markdown. The
  // Placed after the H1 so renderers still treat `# Conformance` as the
  // document title.
  lines.push('<!-- Generated by scripts/generate_conformance_doc.mjs from spec-compliance/registry/*.md. Do not edit by hand — `npm run check:conformance-doc` reverts hand edits. -->');
  lines.push('');
  lines.push(`safe-docx targets a defined subset of **${specFamilyTitle(entries) || 'no specs yet'}**.`);
  lines.push('Each entry below carries a stable serial ID, the section it claims, and a');
  lines.push('binding into a vendored normative schema. Tests carry matching structured');
  lines.push('Allure labels via `testAllure.conformance({…})`; source code carries');
  lines.push('`@conformance` JSDoc tags. The citation-hygiene lint at');
  lines.push('`scripts/check_conformance_citations.mjs` enforces both.');
  lines.push('');
  lines.push('## Targeted sections');
  lines.push('');
  if (entries.length === 0) {
    lines.push('_The registry is empty._');
  } else {
    lines.push('| ID | Title | Edition | Part | Section | Schema reference | Verified by |');
    lines.push('| --- | --- | --- | --- | --- | --- | --- |');
    for (const e of entries) {
      const verified = (e.meta.verifiedBy ?? '').trim() || '—';
      const schemaRef = (e.meta.schemaRef ?? '').trim() || '—';
      lines.push(`| \`${e.id}\` | ${e.title} | ${e.meta.edition ?? '?'} | ${e.meta.part ?? '?'} | ${e.meta.section ?? '?'} | \`${schemaRef}\` | ${verified} |`);
    }
    lines.push('');
    for (const e of entries) {
      renderEntryDetail(lines, e, { includeVerifiedBy: true });
    }
  }

  lines.push('## Non-Goals');
  lines.push('');
  if (registry.nonGoalsPreamble) {
    lines.push(registry.nonGoalsPreamble);
    lines.push('');
  }
  if (nonGoals.length === 0) {
    lines.push('_None yet. As the registry grows, sections explicitly out of scope will be');
    lines.push('listed here so the framework treats "we do not target this" as a first-class');
    lines.push('statement._');
    lines.push('');
  } else {
    // Non-Goals render with the same detail block as targeted sections (minus
    // the Verified-by line — nothing verifies a non-claim) so "we explicitly do
    // not target this" carries the same spec/schema binding as a claim.
    for (const e of nonGoals) {
      renderEntryDetail(lines, e, { includeVerifiedBy: false });
    }
  }
  lines.push(`_Sources: ${registry.sources.map((s) => `\`${s}\``).join(', ') || 'none'}._`);
  lines.push('');
  return lines.join('\n');
}

// ── Main ────────────────────────────────────────────────────────────────────

function main() {
  const registry = loadRegistry();
  const conformanceMd = renderConformanceMd(registry);
  fs.writeFileSync(OUT_CONFORMANCE, conformanceMd);

  console.log(`generate_conformance_doc: wrote ${path.relative(REPO_ROOT, OUT_CONFORMANCE)}`);
}

main();
