#!/usr/bin/env node
// Generates verification/INVARIANTS.md from verification/registry/invariants.json.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REGISTRY_PATH = path.join(REPO_ROOT, 'verification', 'registry', 'invariants.json');
const OUT_PATH = path.join(REPO_ROOT, 'verification', 'INVARIANTS.md');
const TIER_ORDER = ['empirically-validated', 'tested-only'];

const escapeCell = (value) => String(value ?? '—').replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, '<br>');
const code = (value) => value ? `\`${escapeCell(value)}\`` : '—';
const proseList = (values) => Array.isArray(values) && values.length ? values.map(escapeCell).join('<br>') : '—';

function render(registry) {
  const lines = [
    '# Verification Invariants',
    '',
    '<!-- Generated by scripts/generate_invariants_doc.mjs from verification/registry/invariants.json. Do not edit by hand. -->',
    '',
    'This document records deterministic and conventional evidence maintained by safe-docx.',
    '',
    '## Tier Taxonomy',
    '',
    '- `empirically-validated` (established by a deterministic differential harness, property test, or reference-implementation oracle)',
    '- `tested-only` (covered by conventional tests)',
    '',
  ];
  for (const tier of TIER_ORDER) {
    const entries = registry.invariants.filter((entry) => entry.tier === tier);
    if (entries.length === 0) continue;
    lines.push(`## ${tier}`, '', '| ID | Statement | Evidence | Production surface | Caveats | Falsifier |', '| --- | --- | --- | --- | --- | --- |');
    for (const entry of entries) {
      lines.push(`| ${code(entry.id)} | ${escapeCell(entry.statement)} | ${code(entry.evidence)} | ${code(entry.productionSurface)} | ${proseList(entry.caveats)} | ${escapeCell(entry.falsifier)} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

const registry = JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf8'));
fs.writeFileSync(OUT_PATH, render(registry));
console.log(`generate_invariants_doc: wrote ${path.relative(REPO_ROOT, OUT_PATH)}`);
